services:
  web:
    build:
      context: web
      dockerfile: Dockerfile
      target: ${TARGET:-dev}
    ports:
      - 5050:80
    volumes:
      - ./web:/app/web
      - /app/web/node_modules
    depends_on:
      - api
    restart: on-failure:10
    healthcheck:
      test: curl --fail http://localhost:5051/api/users
      start_period: 2s
    networks:
      - full_stack

  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 5051:5000
    volumes:
      - ./api:/app/api
    depends_on:
      - db
    restart: on-failure:10
    healthcheck:
      test: curl --fail http://localhost:33066
      start_period: 2s
    networks:
      - full_stack

  db:
    image: mysql:8.0.25
    restart: on-failure:10
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    # volumes:
    #   - db_data:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - full_stack

# volumes:
#   db_data: {}


networks:
  full_stack: {}
