name: ci-cd

on:
  push:

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/front-end
          tags: |
            type=sha,prefix=,suffix=
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push front-end application
        uses: docker/build-push-action@v6
        with:
          context: web
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          target: prod-static

      - name: Docker meta
        id: meta-back-end
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/back-end
          tags: |
            type=sha,prefix=,suffix=

      - name: Build and push back-end application
        uses: docker/build-push-action@v6
        with:
          context: api
          push: true
          tags: ${{ steps.meta-back-end.outputs.tags }}

  build-and-push-helm-charts:
    needs: build-and-push-images
    runs-on: ubuntu-latest
    env:
      TIMESTAMP: ${{ github.run_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Package and push helm chart for front-end
        run: |
          hash=$(git rev-parse --short HEAD)
          VERSION=0.2.$TIMESTAMP
          echo ${{ secrets.DOCKERHUB_TOKEN }} | helm registry login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          helm package charts/front-end --version $VERSION --app-version $hash
          helm push front-end-$VERSION.tgz oci://registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}

      - name: Package and push helm chart for back-end
        run: |
          VERSION=0.2.$TIMESTAMP
          hash=$(git rev-parse --short HEAD)
          echo ${{ secrets.DOCKERHUB_TOKEN }} | helm registry login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          helm package charts/back-end --version $VERSION --app-version $hash
          helm push back-end-$VERSION.tgz oci://registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}

      - name: Package and push helm chart for MySQL DB
        run: |
          VERSION=0.2.$TIMESTAMP
          hash=$(git rev-parse --short HEAD)
          echo ${{ secrets.DOCKERHUB_TOKEN }} | helm registry login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          helm package charts/mysql --version $VERSION --app-version $hash
          helm push db-$VERSION.tgz oci://registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}
